task:
  name: Jackal
  physics_engine: ${..physics_engine}
  env:
    numEnvs: ${resolve_default:4096,${...num_envs}}
    envSpacing: 8.0
    resetDist: 3.0
    maxEffort: 400.0
    maxEpisodeLength: 150
    noiseAmount: 0.0
    clipActions: 5.0
    controlFrequencyInv: 4
    renderImages: true
    linearVelocity: 2.0
    linearVelocityTurn: 1.0
    angularVelocity: 15.0
    robotXLower: -1.5
    robotXUpper: 1.5
    robotYLower: -0.3
    robotYUpper: 0.2
    robotYawLower: 0.0
    robotYawUpper: 3.14
    doorLower: -0.3
    doorUpper: 0.3
  sim:
    dt: 0.01
    use_gpu_pipeline: ${eq:${...pipeline},"gpu"}
    gravity:
    - 0.0
    - 0.0
    - -9.81
    add_ground_plane: false
    add_distant_light: true
    use_flatcache: true
    enable_scene_query_support: false
    enable_cameras: true
    default_physics_material:
      static_friction: 1.0
      dynamic_friction: 1.0
      restitution: 0.0
    physx:
      worker_thread_count: ${....num_threads}
      solver_type: ${....solver_type}
      use_gpu: ${eq:${....sim_device},"gpu"}
      solver_position_iteration_count: 4
      solver_velocity_iteration_count: 0
      contact_offset: 0.02
      rest_offset: 0.001
      bounce_threshold_velocity: 0.2
      friction_offset_threshold: 0.04
      friction_correlation_distance: 0.025
      enable_sleeping: true
      enable_stabilization: true
      max_depenetration_velocity: 100.0
      gpu_max_rigid_contact_count: 519952
      gpu_max_rigid_patch_count: 519952
      gpu_found_lost_pairs_capacity: 296442
      gpu_found_lost_aggregate_pairs_capacity: 1048576
      gpu_total_aggregate_pairs_capacity: 524288
      gpu_max_soft_body_contacts: 1048576
      gpu_max_particle_contacts: 1048576
      gpu_heap_capacity: 67108864
      gpu_temp_buffer_capacity: 16777216
      gpu_max_num_partitions: 8
    Jackal:
      override_usd_defaults: false
      enable_self_collisions: false
      enable_gyroscopic_forces: true
      solver_position_iteration_count: 4
      solver_velocity_iteration_count: 0
      sleep_threshold: 0.005
      stabilization_threshold: 0.001
      density: 2500
      max_depenetration_velocity: 100.0
      contact_offset: 0.02
      rest_offset: 0.001
    Wall:
      override_usd_defaults: false
      make_kinematic: true
      enable_self_collisions: false
      enable_gyroscopic_forces: true
      solver_position_iteration_count: 4
      solver_velocity_iteration_count: 0
      sleep_threshold: 0.005
      stabilization_threshold: 0.001
      density: -1
      max_depenetration_velocity: 100.0
      contact_offset: 0.02
      rest_offset: 0.001
    Left_Door:
      override_usd_defaults: true
      make_kinematic: true
      enable_self_collisions: false
      enable_gyroscopic_forces: true
      solver_position_iteration_count: 4
      solver_velocity_iteration_count: 0
      sleep_threshold: 0.005
      stabilization_threshold: 0.001
      density: -1
      max_depenetration_velocity: 100.0
      contact_offset: 0.02
      rest_offset: 0.001
    Right_Door:
      override_usd_defaults: true
      make_kinematic: true
      enable_self_collisions: false
      enable_gyroscopic_forces: true
      solver_position_iteration_count: 4
      solver_velocity_iteration_count: 0
      sleep_threshold: 0.005
      stabilization_threshold: 0.001
      density: -1
      max_depenetration_velocity: 100.0
      contact_offset: 0.02
      rest_offset: 0.001
train:
  params:
    seed: ${...seed}
    algo:
      name: a2c_discrete
    model:
      name: discrete_a2c
    network:
      name: actor_critic
      separate: true
      space:
        discrete: null
      mlp:
        units:
        - 256
        - 256
        - 128
        activation: elu
        initializer:
          name: default
        regularizer:
          name: None
    load_checkpoint: ${if:${...checkpoint},True,False}
    load_path: ${...checkpoint}
    config:
      name: ${resolve_default:Jackal,${....experiment}}
      full_experiment_name: ${.name}
      device: ${....rl_device}
      device_name: ${....rl_device}
      multi_gpu: ${....multi_gpu}
      env_name: rlgpu
      ppo: true
      mixed_precision: true
      normalize_input: true
      normalize_value: true
      value_bootstrap: true
      num_actors: ${....task.env.numEnvs}
      reward_shaper:
        scale_value: 0.01
      normalize_advantage: true
      gamma: 0.99
      tau: 0.95
      learning_rate: 0.0003
      lr_schedule: adaptive
      schedule_type: legacy
      kl_threshold: 0.008
      score_to_win: 20000
      max_epochs: ${resolve_default:3000,${....max_iterations}}
      save_best_after: 50
      save_frequency: 25
      grad_norm: 1.0
      entropy_coef: 0.01
      truncate_grads: true
      e_clip: 0.2
      horizon_length: 16
      minibatch_size: 32768
      mini_epochs: 4
      critic_coef: 2
      clip_value: true
      seq_len: 4
      bounds_loss_coef: 0.0001
task_name: ${task.name}
experiment: ''
num_envs: 1
seed: 42
torch_deterministic: false
max_iterations: ''
physics_engine: physx
pipeline: gpu
sim_device: gpu
device_id: 0
rl_device: cuda:0
multi_gpu: false
num_threads: 4
solver_type: 1
test: true
checkpoint: /workspace/omniisaacgymenvs/omniisaacgymenvs/runs/Jackal/nn/Jackal.pth
headless: true
enable_livestream: true
mt_timeout: 30
wandb_activate: true
wandb_group: Jackal
wandb_name: ${train.params.config.name}
wandb_entity: jcoll44
wandb_project: omniisaacgymenvs
